backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow

media_folder: 'public/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'post'
    label: '文章'
    folder: 'posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: '描述', name: 'description', widget: 'text' }
      # tags list string
      - { label: '标签', name: 'tags', widget: 'list', field: { label: '标签', name: 'tag', widget: 'string' } }
      - { label: '正文', name: 'body', widget: 'markdown' }
